import type {
  EmailTemplateRecord,
  GmailInquiryMessage,
  LeadRecord,
  LeadQualificationRecord,
  LeadStatus,
  ListingRecord,
  QualificationRuleRecord,
  TeamUser,
} from "@/lib/types";

const pwHash = "$2b$10$C5YOhMLFQgwRfySkzWf0JeEFnWzrbeZSvf524qw3HvNhnXeHNdvpW";

export const seedUsers: TeamUser[] = [
  {
    id: "user_admin",
    name: "Ariana Chen",
    email: "Admin@srealty.nyc",
    phone: "212-555-1100",
    role: "ADMIN",
    passwordHash: pwHash,
    isActive: true,
  },
  {
    id: "user_agent_1",
    name: "Marcus Bell",
    email: "mbell@sovereignnyc.com",
    phone: "212-555-2200",
    role: "AGENT",
    passwordHash: pwHash,
    isActive: true,
  },
  {
    id: "user_assistant_1",
    name: "Sofia Ruiz",
    email: "ops@sovereignnyc.com",
    phone: "212-555-3300",
    role: "ASSISTANT",
    passwordHash: pwHash,
    isActive: true,
  },
  {
    id: "user_viewer_1",
    name: "Reporting Viewer",
    email: "viewer@sovereignnyc.com",
    role: "READ_ONLY",
    passwordHash: pwHash,
    isActive: true,
  },
];

export const seedListings: ListingRecord[] = [
  {
    id: "listing_tribeca_2a",
    address: "101 Warren St",
    apartmentNumber: "2A",
    rent: 5200,
    beds: 2,
    baths: 1,
    neighborhood: "Tribeca",
    availabilityDate: "2026-06-20T00:00:00.000Z",
    agentId: "user_agent_1",
    showingInstructions: "24-hour notice. Building concierge check-in required.",
    petPolicy: "Cats allowed, small dogs case-by-case",
    incomeRequirementX: 40,
    guarantorRequirementX: 80,
    brokerFeeStatus: "No Fee",
    platformLinks: {
      streeteasy: "https://streeteasy.com/building/101-warren-st-2a",
      realtymx: "https://realtymx.com/listings/101-warren-2a",
    },
    status: "ACTIVE",
  },
  {
    id: "listing_ues_11f",
    address: "245 E 87th St",
    apartmentNumber: "11F",
    rent: 3600,
    beds: 1,
    baths: 1,
    neighborhood: "Upper East Side",
    availabilityDate: "2026-06-15T00:00:00.000Z",
    agentId: "user_agent_1",
    showingInstructions: "Tenant occupied. Tuesday/Thursday showings only.",
    petPolicy: "No dogs, cats allowed",
    incomeRequirementX: 40,
    guarantorRequirementX: 80,
    brokerFeeStatus: "15% Fee",
    platformLinks: {
      zillow: "https://www.zillow.com/homedetails/245-E-87th-St-11F",
    },
    status: "ACTIVE",
  },
];

export const seedLeads: LeadRecord[] = [
  {
    id: "lead_jordan_1",
    clientName: "Jordan Smith",
    email: "jordan.smith@email.com",
    phone: "917-555-9911",
    originalSender: "Jordan Smith <jordan.smith@email.com>",
    inquirySubject: "Inquiry for 101 Warren St 2A",
    listingId: "listing_tribeca_2a",
    source: "STREETEASY",
    inquiryMessage:
      "Hi, I am interested in 101 Warren St 2A. Looking to move by July 1st. We are 2 working professionals with one cat.",
    desiredMoveInDate: "2026-07-01T00:00:00.000Z",
    budget: 5600,
    pets: "1 cat",
    occupants: 2,
    annualIncome: 235000,
    employmentDetails: "Both full-time employed",
    needsGuarantor: false,
    creditReadiness: "700+",
    gmailMessageId: "gmail_seed_msg_001",
    gmailThreadId: "gmail_seed_thread_001",
    gmailImportedAt: "2026-06-03T14:10:00.000Z",
    sourceDetectionResult: "STREETEASY",
    sourceDetectionConfidence: 0.95,
    listingMatchConfidence: 0.92,
    listingMatchReason: "Matched exact address + apartment from inquiry text.",
    missingFields: [],
    showingAvailability: "Tue after 5pm",
    status: "QUALIFIED",
    score: 86,
    qualificationReason: "Income and occupancy fit listing requirements.",
    responsivenessScore: 80,
    completenessScore: 90,
    recommendedNextAction: "Offer showing slots for this week.",
    assignedAgentId: "user_agent_1",
    followUpDate: "2026-06-04T15:00:00.000Z",
    receivedAt: "2026-06-03T14:10:00.000Z",
    parsedFields: {
      listingAddress: "101 Warren St",
      apartmentNumber: "2A",
      sourcePlatform: "StreetEasy",
    },
  },
  {
    id: "lead_priya_1",
    clientName: "Priya Patel",
    email: "priya@email.com",
    originalSender: "Priya Patel <priya@email.com>",
    inquirySubject: "Website inquiry - 245 E 87th St 11F",
    listingId: "listing_ues_11f",
    source: "WEBSITE",
    inquiryMessage:
      "Interested in 245 E 87th St apt 11F. I am a student with guarantor support and flexible move-in date.",
    desiredMoveInDate: "2026-06-22T00:00:00.000Z",
    budget: 3500,
    pets: "No pets",
    occupants: 1,
    annualIncome: 42000,
    employmentDetails: "Graduate student",
    needsGuarantor: true,
    creditReadiness: "Limited history",
    gmailMessageId: "gmail_seed_msg_002",
    gmailThreadId: "gmail_seed_thread_002",
    gmailImportedAt: "2026-06-03T16:40:00.000Z",
    sourceDetectionResult: "WEBSITE",
    sourceDetectionConfidence: 0.71,
    listingMatchConfidence: 0.86,
    listingMatchReason: "Matched listing URL and unit in message body.",
    missingFields: ["guarantor documents"],
    status: "POSSIBLY_QUALIFIED",
    score: 61,
    qualificationReason: "Requires guarantor income verification.",
    responsivenessScore: 70,
    completenessScore: 75,
    recommendedNextAction: "Request guarantor documents and preferred showing windows.",
    receivedAt: "2026-06-03T16:40:00.000Z",
    parsedFields: {
      listingAddress: "245 E 87th St",
      apartmentNumber: "11F",
      sourcePlatform: "Website",
    },
  },
  {
    id: "lead_lee_1",
    clientName: "Daniel Lee",
    email: "dlee@email.com",
    originalSender: "Daniel Lee <dlee@email.com>",
    inquirySubject: "Is this apartment still available?",
    source: "DIRECT_EMAIL",
    inquiryMessage:
      "Hello, is your Tribeca 2 bedroom still available? We can move immediately but have not finalized income docs yet.",
    budget: 4800,
    pets: "Dog",
    occupants: 3,
    sourceDetectionResult: "DIRECT_EMAIL",
    sourceDetectionConfidence: 0.64,
    listingMatchConfidence: 0.43,
    listingMatchReason: "Possible neighborhood mention only; unit not confirmed.",
    missingFields: ["annual income", "move-in date", "showing availability"],
    status: "NEEDS_REVIEW",
    score: 38,
    qualificationReason: "Missing income details and pet policy mismatch risk.",
    responsivenessScore: 60,
    completenessScore: 40,
    recommendedNextAction: "Send qualification questionnaire and clarify pet policy.",
    receivedAt: "2026-06-03T17:20:00.000Z",
    parsedFields: {
      listingAddress: "101 Warren St",
      sourcePlatform: "Email",
    },
  },
];

export const seedQualificationRules: QualificationRuleRecord[] = [
  {
    id: "rule_income_default",
    name: "Default Income-to-Rent Requirement",
    description: "Household income should be at least 40x monthly rent.",
    isActive: true,
    weight: 30,
    criteria: {
      incomeMultiple: 40,
      guarantorMultiple: 80,
    },
  },
  {
    id: "rule_movein_window",
    name: "Move-In Window",
    description: "Move-in should be within 60 days of inquiry.",
    isActive: true,
    weight: 15,
    criteria: {
      moveInWindowDays: 60,
    },
  },
  {
    id: "rule_pet_fit_tribeca",
    name: "Tribeca Pet Fit",
    description: "Tribeca listing accepts cats and small dogs only.",
    listingId: "listing_tribeca_2a",
    isActive: true,
    weight: 10,
    criteria: {
      allowPets: true,
    },
  },
];

export const seedTemplates: EmailTemplateRecord[] = [
  {
    id: "template_initial_reply",
    name: "Initial Qualification Reply",
    category: "INITIAL_REPLY",
    mode: "DRAFT_REVIEW",
    subject: "Thanks for your inquiry about {{listing_address}} {{apartment_number}}",
    body:
      "Hi {{client_name}},\n\nThanks for your interest in {{listing_address}} {{apartment_number}} (rent: ${{rent}}). To help us schedule the right next steps, can you confirm your ideal move-in date, household size, pets, annual income, guarantor need, and showing availability this week?\n\nBest,\n{{agent_name}}\nSovereign Realty NYC",
    isActive: true,
  },
  {
    id: "template_followup_24h",
    name: "Follow-Up 24h",
    category: "FOLLOW_UP",
    mode: "DRAFT_REVIEW",
    subject: "Quick follow-up on {{listing_address}}",
    body:
      "Hi {{client_name}},\n\nJust checking in regarding your inquiry on {{listing_address}} {{apartment_number}}. If you are still interested, share your preferred showing times and qualification details so we can move quickly.\n\nBest,\n{{agent_name}}",
    isActive: true,
  },
  {
    id: "template_application_ready",
    name: "Application Readiness",
    category: "APPLICATION",
    mode: "DRAFT_REVIEW",
    subject: "Application instructions for {{listing_address}}",
    body:
      "Hi {{client_name}},\n\nGreat news — based on your profile, you can begin the application process. Please submit: photo ID, proof of income, bank statements, and guarantor documents if needed. Application link: {{application_link}}\n\nThanks,\n{{agent_name}}",
    isActive: true,
  },
];

export const seedQualifications: LeadQualificationRecord[] = [
  {
    id: "qual_1",
    leadId: "lead_jordan_1",
    listingId: "listing_tribeca_2a",
    status: "QUALIFIED",
    score: 86,
    notes: "Income and occupancy strongly match requirements.",
    reasons: ["Income exceeds 40x rent", "Move-in timeline fits", "Pet policy compatible"],
    evaluatedAt: "2026-06-03T14:15:00.000Z",
  },
  {
    id: "qual_2",
    leadId: "lead_priya_1",
    listingId: "listing_ues_11f",
    status: "POSSIBLY_QUALIFIED",
    score: 61,
    notes: "Guarantor path may qualify the lead.",
    reasons: ["Needs guarantor verification", "Move-in timeline fits"],
    evaluatedAt: "2026-06-03T16:50:00.000Z",
  },
];

export const seedEmailMessages = [
  {
    id: "msg_1",
    leadId: "lead_jordan_1",
    direction: "INBOUND" as const,
    subject: "Inquiry for 101 Warren St 2A",
    bodyText:
      "Hi, I am interested in 101 Warren St 2A. Looking to move by July 1st. We are 2 working professionals with one cat.",
    senderEmail: "jordan.smith@email.com",
    recipientEmail: "leasing@sovereignnyc.com",
    gmailMessageId: "gmail_seed_msg_001",
    gmailThreadId: "gmail_seed_thread_001",
    sentAt: "2026-06-03T14:10:00.000Z",
    status: "RECEIVED",
  },
  {
    id: "msg_2",
    leadId: "lead_jordan_1",
    direction: "OUTBOUND" as const,
    subject: "Re: Inquiry for 101 Warren St 2A",
    bodyText:
      "Thanks Jordan. Can you share household annual income and preferred showing windows this week?",
    senderEmail: "mbell@sovereignnyc.com",
    recipientEmail: "jordan.smith@email.com",
    gmailMessageId: "gmail_seed_msg_003",
    gmailThreadId: "gmail_seed_thread_001",
    sentAt: "2026-06-03T14:20:00.000Z",
    status: "SENT",
  },
  {
    id: "msg_3",
    leadId: "lead_priya_1",
    direction: "INBOUND" as const,
    subject: "Website inquiry - 245 E 87th St 11F",
    bodyText:
      "Interested in 245 E 87th St apt 11F. I am a student with guarantor support and flexible move-in date.",
    senderEmail: "priya@email.com",
    recipientEmail: "leasing@sovereignnyc.com",
    gmailMessageId: "gmail_seed_msg_002",
    gmailThreadId: "gmail_seed_thread_002",
    sentAt: "2026-06-03T16:40:00.000Z",
    status: "RECEIVED",
  },
];

export const seedLeadNotes = [
  {
    id: "note_1",
    leadId: "lead_priya_1",
    authorId: "user_assistant_1",
    content: "Requested guarantor employment letter and tax return summary.",
    createdAt: "2026-06-03T16:55:00.000Z",
  },
];

export const seedMockGmailMessages: GmailInquiryMessage[] = [
  {
    id: "gmail_mock_001",
    threadId: "gmail_mock_thread_001",
    subject: "StreetEasy inquiry for 101 Warren St 2A",
    bodyText:
      "Hi, I am interested in this apartment. Is this still available? My budget is $5400 and we are two occupants with one cat. Move in July 5.",
    snippet: "StreetEasy inquiry for 101 Warren St 2A. Is this still available?",
    fromEmail: "nina.brooks@email.com",
    fromName: "Nina Brooks",
    receivedAt: "2026-06-04T14:20:00.000Z",
    source: "STREETEASY",
    sourceFilter: "STREETEASY",
    sourceConfidence: 0.94,
    isInquiry: true,
    listingLink: "https://streeteasy.com/building/101-warren-st-2a",
  },
  {
    id: "gmail_mock_002",
    threadId: "gmail_mock_thread_002",
    subject: "Zillow lead: 52 W 95th St Apt 4B",
    bodyText:
      "Hi Sovereign Team, I found this on Zillow and I am interested in 52 W 95th St Apt 4B. Can I schedule a showing this Thursday? Budget $4200. Annual income $146,000.",
    snippet: "Zillow lead for 52 W 95th St Apt 4B, asks to schedule a showing.",
    fromEmail: "olivia.ramirez@email.com",
    fromName: "Olivia Ramirez",
    receivedAt: "2026-06-04T15:03:00.000Z",
    source: "ZILLOW",
    sourceFilter: "ZILLOW",
    sourceConfidence: 0.91,
    isInquiry: true,
    listingLink: "https://www.zillow.com/homedetails/52-W-95th-St-4B-New-York-NY",
  },
  {
    id: "gmail_mock_003",
    threadId: "gmail_mock_thread_003",
    subject: "RealtyMX inquiry - 315 W 33rd St Unit 7C",
    bodyText:
      "RealtyMX Inquiry: Client requests details for 315 W 33rd St Unit 7C. Household of 3, no pets, move-in date August 1.",
    snippet: "RealtyMX inquiry for 315 W 33rd St Unit 7C.",
    fromEmail: "inquiries@realtymx.com",
    fromName: "RealtyMX Leads",
    receivedAt: "2026-06-04T15:40:00.000Z",
    source: "REALTYMX",
    sourceFilter: "REALTYMX",
    sourceConfidence: 0.89,
    isInquiry: true,
  },
  {
    id: "gmail_mock_004",
    threadId: "gmail_mock_thread_004",
    subject: "Website Contact Form: Interested in 245 E 87th St 11F",
    bodyText:
      "Message from sovereignrealtynyc.com form. Name: Priya. Looking for August move-in for 245 E 87th St 11F. Income $180,000. Has guarantor available.",
    snippet: "Website contact form inquiry for 245 E 87th St 11F.",
    fromEmail: "webform@sovereignrealtynyc.com",
    fromName: "Sovereign Website",
    receivedAt: "2026-06-04T16:08:00.000Z",
    source: "WEBSITE",
    sourceFilter: "WEBSITE",
    sourceConfidence: 0.86,
    isInquiry: true,
  },
  {
    id: "gmail_mock_005",
    threadId: "gmail_mock_thread_005",
    subject: "Can I schedule a showing? 245 E 87th St apt 11F",
    bodyText:
      "I'm interested in apartment 11F at 245 E 87th St. I can show Tuesday evening. Annual income around $155,000. No pets.",
    snippet: "Direct client email asking to schedule a showing.",
    fromEmail: "ethan.wu@email.com",
    fromName: "Ethan Wu",
    receivedAt: "2026-06-04T16:33:00.000Z",
    source: "DIRECT_EMAIL",
    sourceFilter: "DIRECT_EMAIL",
    sourceConfidence: 0.81,
    isInquiry: true,
  },
  {
    id: "gmail_mock_006",
    threadId: "gmail_mock_thread_006",
    subject: "Weekly market newsletter",
    bodyText: "Here is this week's market update and sponsor highlights.",
    snippet: "Weekly market newsletter and sponsor highlights.",
    fromEmail: "newsletter@marketwatch.com",
    fromName: "Market Watch",
    receivedAt: "2026-06-04T18:00:00.000Z",
    source: "UNKNOWN",
    sourceFilter: "UNKNOWN",
    sourceConfidence: 0.22,
    isInquiry: false,
  },
];

export const seedFollowUpPlan = {
  name: "Default leasing follow-up",
  steps: [
    { step: 1, delayHours: 0, template: "Initial reply" },
    { step: 2, delayHours: 24, template: "Follow-up 24h" },
    { step: 3, delayHours: 48, template: "Follow-up 48h" },
    { step: 4, delayHours: 144, template: "Final follow-up" },
  ],
};

export function createLeadStatusSummary(leads: LeadRecord[]): Record<LeadStatus, number> {
  return leads.reduce(
    (acc, lead) => {
      acc[lead.status] += 1;
      return acc;
    },
    {
      NEW: 0,
      IMPORTED: 0,
      NEEDS_REVIEW: 0,
      DRAFT_CREATED: 0,
      REPLIED: 0,
      FOLLOW_UP_NEEDED: 0,
      NEEDS_REPLY: 0,
      NEEDS_MORE_INFO: 0,
      POSSIBLY_QUALIFIED: 0,
      QUALIFIED: 0,
      NOT_QUALIFIED: 0,
      FOLLOW_UP: 0,
      SHOWING_REQUESTED: 0,
      APPLICATION_REQUESTED: 0,
      ARCHIVED: 0,
    },
  );
}
